export const ADD_MESSAGE = 'ADD_MESSAGE'

export const GET_MESSAGES_PENDING = 'GET_MESSAGES_PENDING'
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS'
export const GET_MESSAGES_ERROR = 'GET_MESSAGES_ERROR'